version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    versioning-strategy: auto
    groups:
      dev-dependencies:
        patterns:
          - '@types/*'
          - '@antfu/*'
          - 'eslint*'
          - typescript
      production-dependencies:
        patterns:
          - '@atproto/*'
          - '@vercel/*'
          - '@supabase/*'
    ignore:
      - dependency-name: typescript
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
